# See ./README for additional information on context and usage

# REQUIRED #
account_id: ""  # The 12-digit number shown directly under the nws-diss-hydrovis-dev account (at https://noaa-prod.awsapps.com/start)
profile: ""  # The name of your profile created via sso configure and used in "aws sso login --profile <profile>"
personal_tag: "your-name"  # No whitespace. This tag will replace "ti" in the naming of all your custom resources (e.g. "hv-vpp-your-name-viz-pipeline")
# END REQUIRED #

# OPTIONAL #
fim_version: ""  # Only set if you are developing the hand-fim-processing lambda
hand_version: ""  # Only set if you are developing the hand-fim-processing lambda
egis_portal_password: ""  # Only set if you are developing the publish-service lambda. This is the password for the hydrovis.proc account.
# END OPTIONAL #

# MAIN #
deploy_resources:  # Set to true for any resources you want to deploy your own copy of
  viz-pipeline: true  # step function
  initialize-pipeline: false  # lambdas from here down
  db-postprocess-sql: false
  optimize-rasters: false
  hand-fim-processing: false  # this provides both the lambda and the step-function
  schism-fim-processing: false # this provides both the lambda and the step-function
  raster-processing: false
  db-ingest: false
  fim-data-prep: false
  publish-service: false
  update-egis-data: false
  python-preprocessing: false